- name: Instalação do nginx
  apt:
    name: nginx
    state: present

- name: Copiar arquivo de hosts do Ansible
  copy: 
    src: /etc/ansible/hosts
    dest: /tmp

- name: Instalação de pacotes
  apt:
    name: {{ packages }}
  state: latest
  vars:
    packages:
      - net-tools 
      - vim
      - nmap

- name: Desabilitar o seviço do nginx