---
- hosts: local
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:
    - name: Create a container with limited
      docker_container:
        name: my-container
        image: ubuntu:17.04
        command: ["sleep", "infinity"]
        
...