---
- hosts: aws
  tasks:
    #Part 1 (Searching for updates)
    - name: Check for updates
      become_user: root
      apt:
        update_cache: yes
        upgrade: yes
    - name: Cleaning packages
      apt:
        autoclean: yes
    - name: Remove dependencies
      apt:
        autoremove: yes
    # Part 2 (Installing new programs)
    - name: Installing new programs for Ubuntu System (Debian based)
      apt: name={{ item }} state=present
      with_itens:
        - ubuntu-restricted-extras
        - vlc
        - gimp
        - pinta
        - shutter
        - gnome-tweak-tool
        - vim
        - openssh-server
        - openssh-client
    - name: Downloading package .deb from internet
      apt: 
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Install Google Chrome
    
    # Configuring another files
    - name: Adding new files
      apt:
        state: latest
    - name: sdsdsd
      apt:
        state: latest



...