---
#Adicionar os arquivos de configuração mais usados no sistema.
- hosts: local
  tasks: 
    - name: Check for updates
      apt:
        update_cache: yes
        upgrade: yes
    - name: Cleaning packages
      apt:
        autoclean: yes
    - name: Remove dependencies
      apt:
        autoremove: yes
    - name: Install main apps for Ubuntu System
      apt:
        pkg:
        - ubuntu-restricted-extras
        - vlc
        - gimp
        - pinta
        - shutter
        - gnome-tweak-tool
        - vim
        - spotify
        - atom
        - openssh-server
        - openssh-client
        state: present 
        
    - name: Installing VirtualBox
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian disco contrib"}


...